/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WorksSlugRouteImport } from './routes/works/$slug'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as EnWorksIndexRouteImport } from './routes/en/works/index'
import { Route as EnBlogIndexRouteImport } from './routes/en/blog/index'
import { Route as EnWorksSlugRouteImport } from './routes/en/works/$slug'
import { Route as EnBlogSlugRouteImport } from './routes/en/blog/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnWorksIndexRoute = EnWorksIndexRouteImport.update({
  id: '/en/works/',
  path: '/en/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/en/blog/',
  path: '/en/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnWorksSlugRoute = EnWorksSlugRouteImport.update({
  id: '/en/works/$slug',
  path: '/en/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/en/blog/$slug',
  path: '/en/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/works/$slug': typeof WorksSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/works/': typeof WorksIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/works/$slug': typeof EnWorksSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/works/': typeof EnWorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/works/$slug': typeof WorksSlugRoute
  '/blog': typeof BlogIndexRoute
  '/en': typeof EnIndexRoute
  '/works': typeof WorksIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/works/$slug': typeof EnWorksSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
  '/en/works': typeof EnWorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/works/$slug': typeof WorksSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/works/': typeof WorksIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/works/$slug': typeof EnWorksSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/works/': typeof EnWorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/en/about'
    | '/works/$slug'
    | '/blog/'
    | '/en/'
    | '/works/'
    | '/en/blog/$slug'
    | '/en/works/$slug'
    | '/en/blog/'
    | '/en/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/en/about'
    | '/works/$slug'
    | '/blog'
    | '/en'
    | '/works'
    | '/en/blog/$slug'
    | '/en/works/$slug'
    | '/en/blog'
    | '/en/works'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/en/about'
    | '/works/$slug'
    | '/blog/'
    | '/en/'
    | '/works/'
    | '/en/blog/$slug'
    | '/en/works/$slug'
    | '/en/blog/'
    | '/en/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  WorksSlugRoute: typeof WorksSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnWorksSlugRoute: typeof EnWorksSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
  EnWorksIndexRoute: typeof EnWorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/works/': {
      id: '/en/works/'
      path: '/en/works'
      fullPath: '/en/works/'
      preLoaderRoute: typeof EnWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/en/blog'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/works/$slug': {
      id: '/en/works/$slug'
      path: '/en/works/$slug'
      fullPath: '/en/works/$slug'
      preLoaderRoute: typeof EnWorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/en/blog/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogSlugRoute: BlogSlugRoute,
  EnAboutRoute: EnAboutRoute,
  WorksSlugRoute: WorksSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  EnIndexRoute: EnIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnWorksSlugRoute: EnWorksSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
  EnWorksIndexRoute: EnWorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
